### ISSUE TITLE
Needs Completion and Examples

### ISSUE THREAD

**Issue by krillr** [BenoitZugmeyer/wlcjs#1]
I'd love to see this library finished and released, there are quite a few NodeJS window managers for X but none for Wayland -- and I think that's because nobody has released good wayland, swl, or wlc bindings for node.

I'm willing to donate some money to see this done, if you're interested.

**Comment by BenoitZugmeyer** [comment]
Thank you for your interest. I have little motivation for my side projects right now but it's nice to see this kind of message. I'll try to continue this project.

If you have some skills in Nodejs or C/C++, I would happily accept contributions. The project is small and not very complicated.

I don't want any money for this, but thanks for proposing.

**Comment by BenoitZugmeyer** [comment]
I finally managed to catch up with the WLC latest API changes, and implemented an example. I guess it solves this issue. Let me know what you think about it.
